"""baseline schema with organization scoping

Revision ID: e9c8f55daefb
Revises: 
Create Date: 2026-09-12 17:32:11.524710
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e9c8f55daefb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('players',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('agent', sa.String(length=60), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('team_a_id', sa.String(length=32), nullable=False),
    sa.Column('team_b_id', sa.String(length=32), nullable=False),
    sa.Column('map', sa.String(length=60), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('played_at', sa.String(length=20), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=False),
    sa.Column('analysis_version', sa.String(length=40), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_map'), 'matches', ['map'], unique=False)
    op.create_index(op.f('ix_matches_organization_id'), 'matches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_matches_team_a_id'), 'matches', ['team_a_id'], unique=False)
    op.create_index(op.f('ix_matches_team_b_id'), 'matches', ['team_b_id'], unique=False)
    op.create_table('team_players',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('jersey', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'player_id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('winner_side', sa.String(length=10), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('vod_start_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_match_id'), 'rounds', ['match_id'], unique=False)
    op.create_table('vods',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vods_match_id'), 'vods', ['match_id'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('vod_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'QUEUED', 'PREPROCESSING', 'DETECTING_ROUNDS', 'TRACKING_PLAYERS', 'DETECTING_EVENTS', 'GENERATING_ANALYTICS', 'COMPLETED', 'FAILED', 'CANCELLED', name='job_status'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('frames_processed', sa.Integer(), nullable=False),
    sa.Column('total_frames', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vod_id'], ['vods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_match_id'), 'analysis_jobs', ['match_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_organization_id'), 'analysis_jobs', ['organization_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('round_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('KILL', 'FIRST_BLOOD', 'DEATH', 'PLANT', 'DEFUSE', 'MID_CONTROL', 'EXECUTE', 'RETAKE', 'ROTATION', name='event_type'), nullable=False),
    sa.Column('t_seconds', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_round_id'), 'events', ['round_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('round_id', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('t_seconds', sa.Float(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('direction', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('team_side', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_player_id'), 'positions', ['player_id'], unique=False)
    op.create_index(op.f('ix_positions_round_id'), 'positions', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_round_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_player_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_events_round_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_analysis_jobs_organization_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_match_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_vods_match_id'), table_name='vods')
    op.drop_table('vods')
    op.drop_index(op.f('ix_rounds_match_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_table('team_players')
    op.drop_index(op.f('ix_matches_team_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_team_a_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_organization_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_map'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('players')
    op.drop_table('organizations')
    # ### end Alembic commands ###
